# Generated by Django 3.0.7 on 2020-06-28 07:27

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-users', 'Usuários')], max_length=12, verbose_name='Icone'),
        ),
    ]
